### ISSUE TITLE
Any plan to have a next release?

### ISSUE THREAD

**Issue by dmiyakawa** [SURFnet/tiqr#50]
I'm interested in the next release for tiqr and possibly tiqr-zf. Is there any plan for the next release?

I'm seeing 1.0.0, which looks very old. Current repository on the other hand has no versioning.
If your implementation is stable enough at this moment, just tagging 2.0.0 (or something like that) will be helpful to me.
Recommending master HEAD (or sha1 hash) to someone else is not comfortable.

**Comment by joostd** [comment]
We will be releasing new version of the tiqr app this week
