### ISSUE TITLE
Problem of garbage characters

### ISSUE THREAD

**Issue by takusng** [SURFnet/tiqr#54]
Dear tiQr developers,

My name is Takuya Matsuhira.
And I'm a technical staff of Kanazawa University, Japan.

I'm preparing to introduce tiQr into the university.

But Japanese version sometimes occurs garbage characters(Especially android).

I'll attach an example of image.
Top page of android  occurs garbage characters.
But top page of iOS doesn't occur garbage characters.

Could you fix garbage characters in order to to use tiQr as a main authentication method of the university?

Regards,
Takuya

![android](https://cloud.githubusercontent.com/assets/10395232/5674933/a380be80-97f6-11e4-9b35-dcafa94d6cb9.jpg)
![iphone](https://cloud.githubusercontent.com/assets/10395232/5674934/a38dcaa8-97f6-11e4-8091-c54ef8b4a3f2.jpg)

**Comment by rijswijk** [comment]
Dear Takuya Matsuhira,

Takuya Matsuhira wrote:
> My name is Takuya Matsuhira.
> And I'm a technical staff of Kanazawa University, Japan.
> 
> I'm preparing to introduce tiQr into the university.
> 
> But Japanese version sometimes occurs garbage characters(Especially
> android).
> 
> I'll attach an example of image.
> Top page of android occurs garbage characters.
> But top page of iOS doesn't occur garbage characters.
> 
> Could you fix garbage characters in order to to use tiQr as a main
> authentication method of the university?

Thank you for contacting us; I have passed your question on to our
developers with the request that they look at this as soon as possible.
One short follow-up question: does the garbling of characters only occur
on certain screens (and if so, which), and does it only occur on certain
Android devices or on all devices you have tested?

Best regards,

Roland

-- 
-- Roland M. van Rijswijk - Deij
-- SURFnet bv
-- w: http://www.surf.nl/en/about-surf/subsidiaries/surfnet
-- e: roland.vanrijswijk@surfnet.nl

**Comment by takusng** [comment]
Dear Roland,
Thank you for your quick reply.

> does the garbling of characters only occur on certain screens (and if so, which),
I find the garbling of characters at another screen.
I attach another example of screen shot(It happened in iOS.).
![attach1](https://cloud.githubusercontent.com/assets/10395232/5677068/3fe0a8e4-9824-11e4-8cf2-3907d91956e1.jpg)

> and does it only occur on certain Android devices or on all devices you have tested?
I think the garbling of characters are occured in both Android and iOS.
the screen which occur the the garbling of characters are different by OS. 
(Almost screens I see are no problem.)

Regards,
Takuya

**Comment by joostd** [comment]
Fixed in new repo (https://github.com/SURFnet/tiqr-client-ios/)
