### ISSUE TITLE
outdated https://tiqr.org/partners/ - clavid no longer exists

### ISSUE THREAD

**Issue by ralfhauser** [SURFnet/tiqr#63]
Swisscom has taken over Clavid approx 2 years ago.
Unfortunately, the stopped TIQR almost immediately.
By Q1/2018 also the rest of Clavid Authentication methods will no longer be available to third partis.

   ==> pls remove dead-link to Clavid and put the post to the archives.

**Comment by joostd** [comment]
Thanks for the heads up. I removed Clavid from our partners page.
